logging:
  pattern.console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-40.40logger{1}){cyan} %msg %n"
  level:
    com.pivotal.rabbitmq.gettingstarted: debug
    com.pivotal.rabbitmq.stream: warn

rabbit:
  default-endpoint-name: standalone
  endpoints:
    standalone:
      port: 5672
      managementPort: 15672
  schema:
    autoLoadSchemas: true
    rootSchemaFolder: /avro
    registryURL: http://localhost:8990
    schemaRegistryStrategy: alwaysRegisterIfNotPresent  # default value


#queue: events-dlq

role: consumer-specific-event-v1
#role: consumer-generic-event-v1
#role: consumer-specific-event-v2
#role: consumer-specific-event-v3
#role: consumer-specific-event-v4
#role: consumer-specific-event-v7

#role: consumerStreamOfCustomer-v2
#role: consumerStreamOfGenericRecord-v2