
logging:
  pattern.console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-40.40logger{1}){cyan} %msg %n"
  level:
    com.pivotal.rabbitmq.gettingstarted: debug
    com.pivotal.rabbitmq.ReactiveRabbitAutoConfiguration: info

role: help

rabbit:
  default-endpoint-name: single
  endpoints:
    cluster:
      port: 5673
    single:
      port: 5672
