spring:
  application:
    name: basic

logging:
  pattern.console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-40.40logger{1}){cyan} %msg %n"
  level:
    com.pivotal.rabbitmq.gettingstarted: debug
    com.pivotal.rabbitmq.stream: warn

role: consumer

rabbit:
  default-endpoint-name: standalone
  endpoints:
    standalone:
      host: localhost
      